fixed mono build
mono does not support this particular variable declaration (Error CS1644: Feature `declaration expression' cannot be used because it is not part of the C# 6.0 language specification (CS1644) (EDSEditorGUI))